project:
  type: book
  output-dir: outputs

book:
  page-navigation: false
  chapters:
    - index.qmd
    - src/01_descriptivo.qmd
    - src/01_tiempo_hasta_estudio.qmd
    - src/02_Ferritina.qmd
    - src/02_Hemogoblina.qmd
    - src/03_similitud_pacientes.qmd
    - src/04_modelos.qmd
  # navbar:
  #   left:
  #     - href: https://www.ufv.es/
  #       image: images/logo.jpg
        # aria-label: "Página UFV"
    # right:
    #   - icon: envelope
    #     href: "mailto:investiga.medicina@ufv.es"
  # sidebar:
  #   tools:
  #     - text: "Contacto"
  #       icon: envelope
  #       href: "mailto:investiga.medicina@ufv.es"
  page-footer:
    center: 
      - text: "UFV"
        href: https://www.ufv.es/

lang: es

format:
  html:
    eval: true
    toc: true
    toc-title: ""
    toc-location: right
    toc-expand: true
    toc-depth: 5
    code-fold: false
    number-sections: false
    self-contained: true
    date-format: "MMMM YYYY"
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 200px
    code-link: true
    css: ../styles.css

editor: source
page-layout: full
knitr:
  opts_chunk:
    fig-width: 12
    fig-height: 5
    out-width: 100%
# code-fold: true
warning: false
message: false
